version: '3.8'

services:
  kq_db:
    image: postgres:15-alpine
    container_name: kq_postgres_prod
    restart: always
    environment:
      - POSTGRES_DB=kqualite_db
      - POSTGRES_USER=kyntus_user
      - POSTGRES_PASSWORD=kyntus_password
    ports:
      - "5433:5432"
    volumes:
      - kq_postgres_data:/var/lib/postgresql/data
    networks:
      - kq-network

  kq_backend:
    build:
      context: ./kqualite
      dockerfile: Dockerfile
    container_name: kq_backend_prod
    restart: always
    ports:
      - "8256:8256" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kq_db:5432/kqualite_db
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SERVER_PORT=8256
      # 🛡️ L'FIX 1: N-3tiw l Java 3 Giga dyal RAM bach y-9der y-9ra l'Excel
      - JAVA_OPTS=-Xmx3g -Xms1g
    depends_on:
      - kq_db
    deploy:
      resources:
        limits:
          # 🛡️ L'FIX 2: N-kebbrou l'limite dyal Docker l 4 Giga
          memory: 4G 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - kq-network

  kq_frontend:
    build:
      context: ./k-qualite-front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://10.10.10.25:8256/api/v1
    container_name: kq_frontend_prod
    restart: always
    ports:
      - "8257:8257"
    environment:
      - PORT=8257
    depends_on:
      - kq_backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - kq-network

volumes:
  kq_postgres_data:

networks:
  kq-network:
    driver: bridge